# Generated by Django 5.0.8 on 2024-08-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('script_path', models.CharField(help_text='Path to parser script', max_length=255)),
                ('schedule_interval', models.CharField(help_text="Дaunch interval, for example, 'daily', 'hourly'", max_length=50)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
