# Generated by Django 5.0.8 on 2024-08-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='schedule_interval',
            field=models.CharField(help_text="Launch interval, e.g., 'daily', 'hourly'", max_length=50),
        ),
        migrations.AlterField(
            model_name='parser',
            name='script_path',
            field=models.FileField(help_text='Path to parser script', upload_to=''),
        ),
    ]
