version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn parceradmin.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - db
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data

  celery:
    build: .
    command: celery -A parceradmin worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A parceradmin beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  redisdata:
