version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data

  celery:
    build: .
    command: celery -A parceradmin worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A parceradmin beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env
