# Generated by Django 4.1.7 on 2024-08-14 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('brand', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('discount_type', models.CharField(choices=[('fix', 'FIX'), ('percentage', 'percentage')], max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('in_stock', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('made_in', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productimages')),
            ],
        ),
    ]
